### ISSUE TITLE
Review unmanaged config - release config and register config?

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#100]
Re-review the unmanaged config. How useful is it? This is very risky and problematic. Please provide a use case for keeping the registration and release. Also need to re-review the builder pattern to see how to best hide it.

**Comment by struberg** [comment]
The unmanaged Config was a use case requested by Gunnar and Romain. It was also discussed and deemed as necessary in 2 hangouts.

The ConfigBuilder is both used for  building the unmanaged Config but also for the programmatically created and registered Config as requested by Gunnar, Romain, Heiko and Anatole and also discussed and agreed on in the hangouts.

For use cases please see the old discussion threads. I personally can live without them, but there were valid arguments pro this functionality.

**Comment by Emily-Jiang** [comment]
I know it was discussed but I cannot recall the valid scenarios. We need to record the scenarios here and document for future references. After my experiments with the specs, I feel it is not useful and it is confusing.

e.g. 
Scenario 1: ClassA and ClassB are having the same classloader
Class A: Config myOwnConfig = ConfigProvider.getBuilder().addSources(...).build()
Class B:  ConfigProvider.getConfig() => return a new one which is different from myOwnConfig
Scenario 2:
Class A: Config myOwnConfig = ConfigProvider.getBuilder().addSources(...).build()
Class A: ConfigProvder.registerConfig(myOwnConfig)
Class B: ConfigProvider.getConfig() => return myOwnConfig

Do you agree that this is tricky? Class B will have a different config if class A decides not to register the config. I thought this further and feel we are better off not to register at all. 

If there is an important use case, please comment here, so that we can see whether we can find alternative solutions.

**Comment by struberg** [comment]
@rmannibucau @asticks and @gunnarmorling might explain their use cases with their own words plz - txs!

**Comment by rmannibucau** [comment]
it is very useful for several use cases like:

- libraries which will read their own config (custom converters which shouldnt leak in the app, potentially custom sources - META-INF/lib/config.properties pattern is common)
- aggregating multiple teams code in a single app requires it too (same reason) and is common in medium/big companies
- custom context management and 3rd party container integration requires it as well
- global configuration (container+apps) requires it too since default impl will never match it (classloader rule will not work and it is unlikely the contextual spi is used since it would break app usage)

**Comment by struberg** [comment]
asticks should be @atsticks I think.

**Comment by Emily-Jiang** [comment]
@rmannibucau thanks for sharing! In your scenarios, do you create a config in one jar and push the config to ConfigProvier and then in a different jar, you try to access it. Right? Where do you release the config? Will this be problematic?

**Comment by rmannibucau** [comment]
No, the config is passed through a different mecanism linked to the environment/framework. To summarize it - a lot - framework.getConfig().

A sample would be shiro reading shiro.ini and converting it to Config for all its internal usage if you want.

The releasing phase depends the integration/framework but is bound to the related lifecycle manager (last point can be a Tomcat listener for instance and the Config instance would be put in each ServletContext in the attribute com.custom.integration.config for example)

**Comment by Emily-Jiang** [comment]
@rmannibucau what is framework.getConfig()? If you pass in the config instance, you don't really need to register it with ConfigProvider, right. You can directly push to the servletcontext. I might misunderstand you. Just trying to understand the use case.

**Comment by Emily-Jiang** [comment]
@struberg it is fine to have two purpose. If there is no registration, the release will not be needed.

**Comment by rmannibucau** [comment]
@struberg any framework ~IoC or way to read the config.

However you still need a close() for the case config components are still managed by the config provider. For example you use a custom Config instance with shiro but keep CDI integration and lookup in the Config provider or you have a ConfigSource which uses CDI.current(). This requires to have a hook to release the instances.

Concretely you can pass all the responsability of the lifecycle outside the config but then it is as efficient and elegant to just not integrate with the config api and just do something else making it not accepted as an API (which is also why i dont think the contextuality belongs here and asked to remove it in another ticket).

**Comment by struberg** [comment]
@rmannibucau yes, fully agree that there is the need. Use ConfigProviderResolver.instance().releaseConfig(Config) for that case!
So I think all your requirements are met.

**Comment by rmannibucau** [comment]
@struberg never said it was not met. was asked to explain why and just did ;).

Side note: my preference goes to Config#close (config would hold the resolver instance internally) cause it avoids the framework to have to manage 2 instances or said otherwise it avoids config api to expose an no more natural API since java 7 autocloseable "trend". However it is 100% equivalent on a feature side of things, agree.

**Comment by struberg** [comment]
Great thanks for clarifying, Romain!

Just to give you an answer why I personally prefer the current way: having a close() on the Config itself will entrap people to also call close() for managed Config instances.

**Comment by OndrejM** [comment]
Actually I§m indifferent, so I§m OK to close it. But @rmannibucau suggestion to have config.close() is cleaner IMHO and can implement autocloseable. Managed instances would be required to simply ignore calls to config and provide an impl-specific method to close it by the container. More complicated for implementors, but cleaner API for users. 

For example, JPA EntityManager also provides [close](http://docs.oracle.com/javaee/6/api/javax/persistence/EntityManager.html#close()) method, which shouldn't be called on a managed instance. However, it would throw an exception instead of simply turning close() to noop on a managed instance.

**Comment by rmannibucau** [comment]
yep, was thinking to IllegalStateException for managed instances

**Comment by OndrejM** [comment]
I would prefer noop for manged instances (without an exception), otherwise people could easily think they should call the close method and would get runtime exceptions. 
Alternatively, it should throw a caught exception to force try catch block and scare people away from using it :) But IMHO a noop implementation is more friendly.
