### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#121]
Fixing some typo in readme, separating impl from "related projects" and changing the term "proposal" into something more appropriate.

**Comment by struberg** [comment]
Wasn't the outcome on the meetings that we do not do 'specifications'?
Because we are 'not a specifications body'?
That's the reason why we worded it that way in the fist place

Not sure what happened about that? @kwsutter @jclingan can you please clarify?

**Comment by keilw** [comment]
@struberg @kwsutter @jclingan or @OndrejM please just suggest a better word? This was not the only change, but @OndrejM said, it should be "specification" instead of "framework". I agree it is a little common, but "framework" or "library" normally do. "proposal" is simply wrong, as this proposal or "requirement" had long been accepted and implemented on ;-)

**Comment by OndrejM** [comment]
@struberg We're not a "standardisation" body, but it doesn't mean we can't create specifications. To me, specification is just a formal document which describes behavior and has nothing to do with standards. And a specification is exactly what we do - we create a description how implementations would behave and what developers can expect. We also provide a TCK, but don't certify any impl - anybody is free to provide an impl and can claim MP compatibility - exactly because we're not a standardisation body.

I don't see any reason why we couldn't use the word specification. It's a common term amd doesn't imply that a specification is considered a "standard". It may become a de facto standard, and eventually a JavaEE JSR, but that would be a different story.

However, if you a better term in mind, I'd welcome any suggestion. Until then, I'm strongly in favor of the term "specification", because it is closest to what we are really doing. We're not building a feamework or library, because we don't target any implementation - without an implementation, MP is just an empty shell, while frameworks and libs can be used right away. We are building an MP platform, composed of separate specifications, some of those specs just happen to be "standard" JSRs, and some are just non-standard specs created within MP.

**Comment by OndrejM** [comment]
BTW, http://www.reactive-streams.org/ also use the word "specification". They even use the word "standard", while they are not a formal standardisation authority nor attempting to submit a standard to such authority, and clearly it isn't a real standard, although they aim to define a de facto standard.

**Comment by keilw** [comment]
Yes, the term TCK is also used. To test against the spec. There are a couple of projects outside major standard bodies, e.g. GWT where TCK is also used. So unless some much better term comes up, I see no problem with spec. We must not call it "standard" at this point (or before;-)

**Comment by Emily-Jiang** [comment]
We can either use Specification or Feature. How does 'Feature' sound?

**Comment by keilw** [comment]
While it means something particular for most Eclipse projects, a non RCP project like MP probably comes across an overlap less, so it could also work.

**Comment by OndrejM** [comment]
"Feature" is not a bad suggestion, but it's a very vague and general term, while the term specification suggests that it involves a formal description. I'd only use it if somebody is really strongly against "specification". Again, I'm not speaking about a specification of a "standard", just plain specification of a feature or behavior.

**Comment by struberg** [comment]
To make more clear what I meant: I'm fine with 'Specification' but was not sure what the Kevin, John etc think about it. Feature seems also fine.

**Comment by keilw** [comment]
Was there a clear agreement on "Specification" or "Feature"?
It's also a question of general terminology either for https://github.com/eclipse/microprofile-evolution-process or maybe use Eclipse Wiki instead?

**Comment by kwsutter** [comment]
I have no issue with either Specification or Feature.  As Mark indicated,
we are not a Standards body, nor do we plan to become one.  But, the word
"specification" is generic enough and does not indicate a "standard".  So,
either word is fine with me.  We should be consistent with the other
"features" being planned for MicroProfile 1.x, so maybe we should get the
consensus answer documented in our evolution process.

Thanks,
Kevin

**Comment by keilw** [comment]
With #135 merged, I'd say this can be closed. Please reopen if you find something was missing.
