### ISSUE TITLE
Using lambda function adding a custom converter does not work

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#124]
Trying to following to create a converter
Converter<String> stringReverser = v -> new StringBuilder(v).reverse().toString();
then use the builder pattern to add the converter.

This stringReverser converter results in a type at runtime of
com.ibm.ws.microprofile.config.converter.test.ConversionTest$$Lambda$1/00000000113C4760@dee71686
with an interface of just
interface org.eclipse.microprofile.config.spi.Converter
(i.e. the <String> parameter has been lost)

**Comment by Emily-Jiang** [comment]
The alternative solution to this problem is to create a property converter class. We could javadoc this limitation by saying:
"The withConverters method uses reflection to determine what Type the converter is for. The custom converters should not be created via Java™ Lambda code, as the Lambda code currently does not offer specific enough Type information to the reflection APIs. Explicitly implementation of a Converter interface is required for a custom converter." Thoughts?

**Comment by struberg** [comment]
That's the type erasure issue I was talking about when I removed the 'default converters' from the API. That's not a limitation of Config but a limitation of how the Java Generics system is working.

**Comment by OndrejM** [comment]
Improving the Javadoc as @Emily-Jiang suggested makes sense because the generic type is lost for lambdas. 

However, it would also make sense to create additional method for a single converter, with a second argument to specify the converter's type - the builder pattern is aimed at power users and they may want to specify exact converter type anyway.

It would be also suitable, if a converter should be declared only for a subtype of it's return type, e.g.:

Converter listConv = s -> Arrays.asList(s.split(",");
builder.withConverter(listConv, ArrayList.class);
builder.withConverter(listConv, LinkedList.class);
// but another converter for all other List subtypes (with lower priority)
builder.withConverter(defaultListConv, List.class);

A third (optional) argument allowing to specify the priority would be handy too, because it's not possible to annotate lambdas with `@Priority` either. But I would leave both suggestions to after Config 1.0.

Btw, playing with the converters API, I realized that we don't have a CDI-based API to define converters yet. I'll create a PR to specify producers for converters. We also don't have such API for ConfigSource and ConfigSourceProvider - each class that can be loaded via Service Loader should be at least considered to be loaded from a CDI producer (unless it's already too late when CDI producers are available)

**Comment by struberg** [comment]
We should probably remove the @FunctionalInterface from Converter, as this will just confuse users.

**Comment by Emily-Jiang** [comment]
improved the javadoc. close this issue now.

**Comment by OndrejM** [comment]
@Emily-Jiang , I don't see any improvement in the javadoc. I created PR #188 to fix that.

**Comment by Emily-Jiang** [comment]
not sure what happened. The PR I promised did not make to the codebase. Thanks @OndrejM !
