### ISSUE TITLE
Config should have a close method 

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#136]
As suggested by @rmannibucau in #57:

> Config should have a close method which is unlinked to the contextuality - think unmanaged case. It can belong to provider too but in term of user API it looks more friendly this way IMHO

**Comment by Emily-Jiang** [comment]
ConfigSource should have a close method.

**Comment by ljnelson** [comment]
Please yes.

**Comment by dmlloyd** [comment]
As of right now, `ConfigSource` is specified to related to `AutoCloseable` as follows:

```java
/**
 * (...)
 *  <p>If a ConfigSource implements the {@link AutoCloseable} interface
 *  then the {@link AutoCloseable#close()} method will be called when
 *  the underlying {@link org.eclipse.microprofile.config.Config} is being released.
 * (...)
 */
```

It is not clear exactly when a config source is released; this language needs to be clarified.  In particular, there is a `org.eclipse.microprofile.config.spi.ConfigProviderResolver#releaseConfig` method; however, it is definitely not clear that calling this method would release the config.  One important detail of this method is that it is allowed (by the current specification) to call `org.eclipse.microprofile.config.spi.ConfigProviderResolver#registerConfig` to register the same `Config` on more than one class loader.  Does `releaseConfig` only release the configuration object from one class loader, or all?  If one, which one?

Making `Config` itself implement `AutoCloseable` with a `close` method seems to be a logical step towards solving this problem.  Then instead of saying "...when the underlying `org.eclipse.microprofile.config.Config` is being released" we can say "...when the underlying `org.eclipse.microprofile.config.Config` is closed by calling its `close()` method".

This doesn't solve the entire problem though, just most of it: for example, `ConfigProvider` specifies that "there is exactly a single `Config` instance per `ClassLoader`", meaning that every class loader must have a `Config` instance, whether or not one was registered.  The implication of this language is that if an implementation is asked for a `Config` corresponding to a `ClassLoader` that doesn't have one, it is required to produce one, and our implementation does so.  But, who then is responsible for calling `close()` on the `Config`?  The naive answer would be to say: the implementation created it, the implementation should destroy it when `releaseConfig` is called.  However, there's nothing stopping the user from taking the returned `Config` instance and registering it for other class loaders, or reusing it after it was automatically created and subsequently released.  This is an accident waiting to happen: either the user may leak `Config` instances because they cannot easily keep track of the auto-created instances, or the user may hit unexpected run time problems when the configuration object is released while they're still using it.  Essentially, there would be no way for the user to know whether it's container managed or user managed: a design red flag.

**Comment by dmlloyd** [comment]
The "most correct" solution to this problem would, in my opinion, be that the specification of `ConfigProviderResolver` must also be updated to indicate that an exception will be thrown when a configuration is requested for a class loader which hasn't registered one.  This ensures that every configuration is explicitly registered, and makes it possible to oblige the API user (typically a container implementation) to track and close configuration objects when they are no longer needed.

**Comment by marekkopecky** [comment]
Based on the discussion with @jmesnil (see https://github.com/wildfly/wildfly/pull/12965#issuecomment-587481304 ), this issue is valid for both `ConfigSource` and `Converter` classes

**Comment by dmlloyd** [comment]
I'll note that neither `ConfigSource` nor `Converter` themselves need to directly implement `AutoCloseable`.  It is sufficient for the implementation's close operation (whatever it is) to detect whether a given `Converter` or `ConfigSource` does so.  But this should be done only if those things are managed by the `Config`, and it is really not clear that they both should be, especially if we introduce an independent framework for converters.

**Comment by Emily-Jiang** [comment]
Based on the discussion, it seems that the implementations can deal with the close activities, so this spec does not need to do anything in particular. Please reopen it if you think otherwise.
