### ISSUE TITLE
Binding Config to an Application

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#161]
The spec uses this phrase in `configprovider`

> If a `Config` is bound to an Application, it gets properly removed if the Application gets destroyed.
> The Config system does not create any memory leaks in that case.

Its not clear what it means to bind a `Config` to an Application.  This seems like it may be an implementation detail since it's referring to memory leaks.

**Comment by struberg** [comment]
Oki, I see what you mean. It's really great that you do a review, because I'm way too deep into it to detect such glitches.

Here is what it's about:
Config instances which are 'bound' to the application are all who are internally stored in a Map<ClassLoader, Config> or Map<Application, Config>. This happens if you either trigger auto-discovery of a Config or if you use the Builder and later register this Config with ConfigProvider#registerConfig.
In those cases we can properly close the Config when the application is about to shutdown.

If you just use a Builder to create a fresh Config instance, then it is _not_ bound to any application yet! So our application also simply cannot know how to destroy it! A user needs to take care of this himself in this very case. Otherwise a mem leak could possibly occur. 

Do you know what I mean?
If so, do you mind to send a PR with a proposal for an alternate wording which expresses this information?

txs and LieGrue,
strub
