### ISSUE TITLE
OSGi support for CDI 2.0 in API

### ISSUE THREAD

**Issue by arjantijms** [eclipse/microprofile-config#249]
Currently the OSGi headers that are generated for the API artefact have a hard exclusion for CDI 2.0. This means in an environment where CDI 2.0 is available, the requirement for a CDI version that's less than 2.0 generally can't be satisfied and the config API won't work.

The problem can be seen as follows:

```bash
unzip -p microprofile-config-api.jar META-INF/MANIFEST.MF
```

```
Manifest-Version: 1.0
Bundle-License: Apache License, Version 2.0
Bundle-SymbolicName: org.eclipse.microprofile.config
Built-By: johnament
Bnd-LastModified: 1504820572283
Bundle-ManifestVersion: 2
Import-Package: javax.enterprise.util;version="[1.1,2)",javax.inject,o
 rg.eclipse.microprofile.config;version="[1.0,2)",org.eclipse.micropro
 file.config.spi;version="[1.1,2)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-3.4.0.201707252008
Export-Package: org.eclipse.microprofile.config;version="1.0";uses:="o
 rg.eclipse.microprofile.config.spi",org.eclipse.microprofile.config.i
 nject;version="1.0";uses:="javax.enterprise.util,javax.inject",org.ec
 lipse.microprofile.config.spi;version="1.1";uses:="org.eclipse.microp
 rofile.config"
Bundle-Name: MicroProfile Config Bundle
Bundle-Version: 1.1.0
Created-By: 1.8.0_101 (Oracle Corporation)
Build-Jdk: 1.8.0_101
```

The problem here is in `Import-Package: javax.enterprise.util;version="[1.1,2)"`

The `2` should become a `3`.

**Comment by OndrejM** [comment]
I don't know it OSGi allows it but there should be no upper boundary on version name - CDI is a JSR therefore every new version should be backward compatible with 1.2 and therefore should work with MP.

**Comment by arjantijms** [comment]
I agree, that could be another option, just don't specify an upper bound at all. I think that's supported indeed.

**Comment by Emily-Jiang** [comment]
That is anti OSGi pattern. The bnd has generated the correct version ranges. It should not include a major version jump. The reason is that major version increases mean binary incompatibilities changes introduced. This could mean a method you used has been deleted. The client will have to be updated. The main issue is that CDI 2.0 has not versioned the packages correctly according to OSGi semantic versioning `https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf.` One workaround is to include 2.0 as the top range but I don't think we should do it right now. We should introduce CDI 2.0 into MicroProfile releases and then all other specs need to cope with CDI 2.0. At the moment, in MP releases, we only have CDI 1.2. We have not pulled in CDI 2.0 as yet. All dependencies are correct in the current release. In the next release, if we pull in CDI 2.0, all dependencies will have to be updated so that all existing specs need to work CDI 2.0.

All JSR leads and EG should understand `https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf` and then proper version their api packages. As for MP APIs, I will try my best to make sure all packages are properly version and the version reflects the changes being made. The same applies to the Config JSR.

**Comment by arjantijms** [comment]
>This could mean a method you used has been deleted. 

It could, theoretically, but in practice, did that happen with CDI 2.0? Is there any method or class indeed deleted in the single package that MP config uses (in this case) or for any package (for all cases)?

The Java EE spec is quite strict about this. In fact, you cannot just remove something without going through a lengthy 2 major release pruning process. As such pruning has not been started in CDI 1.0, nothing can have been deleted in CDI 2.0 (there was one major release 1.1, and one MR 1.2, which doesn't count in this case).

**Comment by Emily-Jiang** [comment]
Then the package version's major digit should not be increased. I have explained the package version in CDI 2.0 was wrong.

**Comment by Emily-Jiang** [comment]
Having that said, in support CDI 2.0, we can update the pom.xml. However, I would like MP to pull in CDI 2.0 first and then all specs will be able to work with CDI 2.0. -1 on no up limit. We have to review the risk case by case. If you want to use config with CDI 2.0, you can do manifest rewrite to workaround this.

**Comment by arjantijms** [comment]
>Then the package version's major digit should not be increased. I have explained the package version in CDI 2.0 was wrong.

Perhaps, versioning is not super consistent either way. CDI 1.0 to 1.1 is a major version, but 1.1 to 1.2 is just a MR. Same for e.g. JSF 2.0 to 2.1 is MR, but 2.1 to 2.2 is major.

The problem is a bit that if breaking changes are the trigger for increasing the major version number, then actually few specs would ever see a major number increase. Almost everything would be at either 0.x or 1.x (depending on where we start).

> -1 on no up limit.

We could do at least 1 minor version number from now, since we know* that nothing will be pruned at least until after CDI 2.1. If CDI 2.1 announces something to be pruned then if I'm not mistaken it can be pruned for CDI 2.2 at the earliest.

_(well, "know", with the OSS transfer things can change, but let's ignore that for a moment here)_

Depending on CDI 2.0 presents the opposite problem, where CDI 1.2 is ruled out, even when the Config spec would not depend on anything CDI 2.0.

>If you want to use config with CDI 2.0, you can do manifest rewrite to workaround this.

That's basically what we do at Payara, or build from the PR that I did.

**Comment by Emily-Jiang** [comment]
We should not mess up between spec version and package version. It is fine to call CDI 2.0, where 2.0 is the spec version. It does not mean the package versions need to be same as spec version. Any packages without any changes from CDI 1.2 and their versions should remain the same. 

When we release a package, the version will be 1.0. If we use semantic versioning correctly, for any JSRs, the version should always stay with 1.x.y. In this way, it is nice and clean.

I am not against the change to support CDI 2.0. My point is that in the next few weeks (after J1), we should be able to pull in CDI 2.0 and then all specs will be updated together.
