### ISSUE TITLE
Revisit Common sense converter 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#269]
https://github.com/eclipse/microprofile-config/issues/248
It added the following support:
=== Automatic Converters

If no built-in nor custom `Converter` for a requested Type `T`, an implicit Converter is automatically provided if the following conditions are met:

* The target type `T` has a Constructor with a String parameter, or
* the target type `T` has a Constructor with a CharSequence parameter, or
* the target type `T` has a `static T valueOf(String)` method, or
* the target type `T` has a `static T valueOf(CharSequence)` method, or
* the target type `T` has a `static T parse(String)` method, or
* the target type `T` has a `static T parse(CharSequence)` method, or
* the target type `T` is an `Enum`, in which case the `Enum#valueOf(Class, String)` is being used.

In the original discussion of #248, I only suggest to add the support 
The target type `T` has a Constructor with a String parameter
the target type `T` has a `static T valueOf(String)` method,

The above will cover most scenarios and it is straightforward.

The current codebase introduces too many variety and we need to specify the search order. I feel this complicates the spec without much gain. What do people think on removing the CharSequence support, parse and Enum. Besides, we are providing a convenient method. If anyone wants to use CharSquence, they can provide their own converter. Thoughts?

**Comment by johnament** [comment]
Please note:

- Fault Tolerance requires the `Enum` type since it doesn't specify that a converter supporting the enums is required.
- In addition, the `Enum` case should be even simpler since `T.valueOf` gets created automatically from any `enum` type.
- The intent of #248 was to change [Pizza.java](https://github.com/eclipse/microprofile-config/blob/1.1/tck/src/main/java/org/eclipse/microprofile/config/tck/converters/Pizza.java#L30) from having a single arg constructor to a 2 arg constructor only (plus change the converter).
- I believe we were capturing ideas for a future release to add common sense conversion to the spec

I would recommend with limiting support to just `String` and not `CharSequence` since `String` is the raw type we use in config without any other requirements.
