### ISSUE TITLE
Get Config master branch back to Config 1.3 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#442]
We discussed today and agreed that we want to revert back to Config 1.3 and then add features gradually.

**Comment by jmesnil** [comment]
I'll create a PR to revert master branch to 1.3.

I'll also look at the PRs that have been merged since 1.3 and cherry-picked the ones that are additional TCKs tests / spec clarification etc.

The idea behind this is to go back to a releasable state for MicroProfile Config 1.x without losing any work that has been done to clarify the existing spec and API

**Comment by dmlloyd** [comment]
This issue can be closed now I think?
