### ISSUE TITLE
Remove wrong "Copyright (c) 2016 IBM Corp. and others" from headers

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-config#45]
Seems sources got "Copyright (c) 2016 IBM Corp. and others" even if the sources are coming from apache repositories and target eclipse so it seems that

    Copyright (c) 2016 IBM Corp. and others

part of the header is inaccurate whatever way (past or future) you check it.

Can you fix it please?

**Comment by struberg** [comment]
I also much prefer the "Copyright Original Author and Authors" over pinning any company.
And again: it is simply wrong that the copyright holder might only be a commercial company. That's plain wrong from a legal pov!

**Comment by Emily-Jiang** [comment]
We have talked about many many times and also discussed in the hangout. It is recommended way for eclipse foundation.

**Comment by keilw** [comment]
The Apache repositories are irrelevant here, sorry but "Copyright Apache Foundation" will not work in an Eclipse project. We addressed this in all relevant projects and if you look at some of the sub-modules, e.g. tck says "Copyright (c) 2016 Mark Struberg and others" as there are repositories with "Copyright (C) 2016, 2017 Antonio Goncalves and others." now. This should be done on a case-by case basis. Applying the RAT plugin like microprofile-samples does ensures, they all share the Apache license, but the individual author(s) may change depending on the initial contribution. @waynebeaton was clear, that other Eclipse projects like SmartHome (where it changed all headers to "Copyright (C) 2016, 2017 by the respective copyright holders" or so) got this wrong, so let's stick to his advise.

**Comment by struberg** [comment]
If that code is taken mainly from an Apache project then "Copyright IBM" is simply wrong. That's what Romain said. Compare the classes with my original proposal (done at Apache) and you will see what I mean.
"Copyright IBM _and others_" is more correct, but still slightly off reality. 

"Copyright Original Author and Authors" is still my favourite and perfectly fine IF it is clear who the original authors have been.

**Comment by keilw** [comment]
If Emily wrote it from scratch (and several classes like `Config`, etc. clearly are, wherever she might have got the inspiration from;-) then "Copyright IBM" is perfectly fine. @waynebeaton said, "Copyright Original Authors" does not meet Eclipse requirements, so please try to convince him/Eclipse or obey those requirements. They may be different in other OS ecosystems.

**Comment by Emily-Jiang** [comment]
I think we should close this in light of Werner's comments and explanation!

**Comment by rmannibucau** [comment]
Just wanted to highlight the comment of Werner is plain wrong and individual contributions can't be considered as company contribution until it is explicitly mentionned and referenced as such. Just cause you work with a company doesn't mean you act for it.

The issue is still valid and the copyright still not correct from a legal POV, now if you dont want to fix it I sadly don't have enough time to fight for it ATM.

**Comment by OndrejM** [comment]
I talked with Emily and we are nor sure how to approach the copyright header, but we didn't want to discuss further. We decided to rather raise the question on Eclipse incubation mailing list. I raised a separate issue #73 to clarify it.

**Comment by struberg** [comment]
Folks, that must be kept open as long as it's not clarified. The copyright headers are currently plain wrong from a legal pov. So we **must** tackle this!

**Comment by keilw** [comment]
Why the overkill, @OndrejM created another one, I think one for this non-issue sounds more than enough https://github.com/eclipse/microprofile-config/issues/73

**Comment by struberg** [comment]
Because this is the older one with more history. We just cannot close a ticket when the underlying problem is not resolved.

**Comment by keilw** [comment]
Link to this one for the history if you think some of it is needed, but not create noise and effort having to close dozens of identical tickets.

**Comment by struberg** [comment]
If you really DO care about avoiding noise, then please finally stop responding to each and every ticket which has nothing to do with you.

**Comment by keilw** [comment]
It does, @Emily-Jiang clearly said here earlier `I think we should close this in light of Werner's comments and explanation!` and reopening it instead of just placing a link in the new one @OndrejM opened creates noise and unnecessary effort so please stop it and try doing something useful.

**Comment by Emily-Jiang** [comment]
I think we wasted a lot of time on this. Mark, you raised this multiple times on various calls and eventually said you were ok with the copyright. Are you guys more interested in getting your names on the copyright instead of working together to finalise the spec? The 'others' on the copyright covers all authors. Is it not enough? If everyone tries to get their names on the copyright and then force to their ideas adopted regardless right or wrong, we won't get anywhere. Please, can we work as a team....

**Comment by rmannibucau** [comment]
Names would work but why not putting just "Eclipse foundation"? We all signed the CLA so it works, is not wrong legally and avoid to promote any company not owning this IP.

**Comment by OndrejM** [comment]
Romain is right - "Eclipse foundation and authors" should be enough provided that authors (and their employers in brackets) are mentioned in the `@author` tags.
P.S. Authors should be those who created a significant portion of the file, not those who added a comment or fixed 1-2 lines of code.

**Comment by Emily-Jiang** [comment]
This conversation is going in circles. Eclipse is not an IP entity and you cannot say license to Eclipse foundation.

**Comment by rmannibucau** [comment]
@Emily-Jiang then what do you propose? Listing all individuals?

**Comment by struberg** [comment]
Someone suggested "Copyright Original Authors or their Employers" (discussion with Eclipse is ongoing)

**Comment by keilw** [comment]
@rmannibucau Yes, that's exactly what https://github.com/eclipse/microprofile-config/issues/88 is about. I quoted an example there, and Hundreds of Eclipse projects keep doing this all the time. As @Emily-Jiang said there's a lot more to do and so many subprojects or modules have not even started, it wastes time trying to act like the Little Gallic Village in Asterix or to "Make Eclipse Apache Again". Apache Foundation may have one kind of header convention, Eclipse or Linux Foundation have theirs.

Check the Linux kernel project, not every file even has copyright notes, but the first one I found https://github.com/torvalds/linux/blob/master/kernel/cgroup/pids.c says
```
* Copyright (C) 2015 Aleksa Sarai <cyphar@cyphar.com>
```

**Comment by struberg** [comment]
@keilw All we want is to avoid IP problems. And the current copyright contribution is for some sources a clear IP breach. And for most others it breaches the Eclipse rules of 'first author attribution'.

**Comment by rmannibucau** [comment]
Exactly, if you read the CLA you signed, most of files don't respect it ATM. My preference is to not mention anyone in particular for sure but if you want it I'm fine with it - since it is not against Eclipse rules and just a preference. It just means individuals should be listed for most of current files.

**Comment by keilw** [comment]
@struberg @rmannibucau Please ask @waynebeaton and his IP team colleagues how 300 active Eclipse projects (http://projects.eclipse.org/list-of-projects has 15 pages with 20 projects each) plus probably as many archived ones by now handled this without problems or IP breach over the past 2 decades. They have full time permanent employees to deal with this. If your or other contributions would violate Eclipse IP rules they would not even be pushed. If it does in Orbit the CQs are not approved.

**Comment by rmannibucau** [comment]
Not sure what you mean @keilw, if you check the headers they match what I said.

**Comment by keilw** [comment]
@rmannibucau @struberg I mean guys you all seem to contribute to CDI and related projects like Weld for a while now, don't you?;-)

https://github.com/cdi-spec/cdi-tck/blob/master/api/src/main/java/org/jboss/cdi/tck/api/Configuration.java
or
https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/bootstrap/AbstractBeanDeployer.java
and every single file in these repositories say
```
 * Copyright 2008, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
```
or similar. Please show us the Red Hat project you or others forced the maintainer to change this into ways you suggested or e.g. Spring may do?

Such "copyright.txt" file or a slight variation of the existing headers like Weld, CDI, Hibernate and every other Red Hat project does, I am sure that's possible. Where Red Hat was the main contributor to Eclipse projects I bet you see similar headers under Eclipse repositories anyway, regardless of them being Apache or Eclipse licensed.

**Comment by rmannibucau** [comment]
I see but this is not the same here cause:

1. code doesnt come from IBM so IP is wrong
2. as an inter-company project I think it should mention all (the "group") or none in particular (not mandatory legally but more than nice to have IMHO)

this ticket should at least fix 1.

**Comment by keilw** [comment]
Can you ask @Emily-Jiang where she works now?;-)
She represents IBM. We heard also from @OndrejM (or via the JCP discussion over @otaviojava) that "smaller" vendors especially Tomitribe or Payara may have a more "creative" and flexible way than hiring people on a permanent basis. So strictly speaking @OndrejM or @otaviojava could be "Individuals" in their own right, but even they all contributed to files like https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/interceptor/builder/InterceptionModelBuilder.java
Which have the same copyright header. 

@Emily-Jiang started the "api" module from scratch, nothing was taken from another project. Both method names and especially JavaDoc are different and in most cases more precise than what you saw in similar files under DeltaSpike or other projecs mentioned. So the original creator (except for the "tck" module but that is why @struberg is mentioned as the initial creator) is IBM. So 1. is wrong and needs no fixing.

**Comment by rmannibucau** [comment]
Just check files history, this is not true.

**Comment by struberg** [comment]
> Emily-Jiang started the "api" module from scratch, nothing was taken from another project. 

Werner, that is NOT correct. Just look at Emilys very first post: https://groups.google.com/d/msg/microprofile/VJEEAOsVj5E/h-3nNEamAQAJ where she even writes herself:

> The API was created with some input from Config JSR presentation on JavaOne from 
> Dmitry Kornilov and Mark Strugberg's initial proposal.

And Dmitrys presentation and prototype are also heavily based on DeltaSpike and Tamaya (I had long hangouts with him when he wrote the proposal).  Where in both I wrote those parts together with Gerhard Petracek. Just look at the classes. I even showed you the commits last year. The design, structure and most code is also still the same. So Copyright IBM is simple wrong.

The original code as extracted from Apache DeltaSpike and proposed to Microprofile in June 2016:
https://github.com/struberg/javaConfig/tree/master/api/src/main/java/io/microprofile/config
https://groups.google.com/d/msg/microprofile/-P7DKyfrK9A/SDxQkuhKCAAJ

<pre>
src/main/java/
└── io
   └── microprofile
       └── config
           ├── Config.java
           ├── ConfigProvider.java
           ├── ConfigValue.java
           └── spi
               ├── ConfigSource.java
               ├── ConfigSourceProvider.java
               └── Converter.java
</pre>

And now look at the current Microprofile API:
https://github.com/eclipse/microprofile-config/tree/master/api/src/main/java/org/eclipse/microprofile/config

<pre>
src/main/java/
└── org
   └── eclipse
       └── microprofile
           └── config
               ├── Config.java
               ├── ConfigProvider.java
               └── spi
                   ├── ConfigProviderResolver.java
                   ├── ConfigSource.java
                   ├── ConfigSourceProvider.java
                   └── Converter.java
</pre>

And of course IBM/Emily did great work and highly deserves to claim authorship on some parts. And she especially was (and still IS) an extremely positive force in pushing Microprofile forward! It was really a community effort. Thus I would love to get a Copyright header which is vendor neutral and emphases the community spirit.

**Comment by keilw** [comment]
If you look at the Config class in greater detail you'll notice it was not copied or extracted but written from scratch. Just because it is called like that mashup of Tamaya, DeltaSpike with some inspiration by Spring or LightBend the class is not taken directly from there. 
"with some input from Config JSR presentation on JavaOne from
Dmitry Kornilov and Mark Strugberg's initial proposal." Sure but input or "inspiration" is not the same as directly copying something. 

It would violate the ECA http://www.eclipse.org/legal/ECA.php to simply copy something even if it's only an "inofficial design study" rather than an official project (like Tamaya, DeltaSpike, Spring etc.) at least it would be similar than if you copied another person's academic work or doctoral thesis ;-)

You must be aware that by making various claims the parallel IP process by Eclipse staff is affected. And files in question may even have to be excluded from a release alltogether. So better try work with @Emily-Jiang as a TEAM like she suggested rather than jeopardizing at least config's inclusion into MP 1.1 or probably longer. I've seen enough cases where IP log took 2 or 3 years, so even with larger strategic members like IBM or Red Hat involved it could take several months till this is ready for release review if everyone keeps shouting "Wer hat's erfunden?" ;-/

**Comment by struberg** [comment]
Werner, you wrote no single line in DeltaSpike, Tamaya or this very codebase. I have no clue why you are even arguing with us who can show code provenance dating back to 2009.

**Comment by keilw** [comment]
You keep claiming @Emily-Jiang copied e.g. the Config class, which is wrong. I contributed to that class helping her to improve the API by getting e.g. method names that don't even exist in either of the other projects in order. See https://github.com/eclipse/microprofile-config/issues/7 The fact, Emily created a PR of her own does not change that this improvement came from me and my ticket. 
And as for Tamaya I am writing entire extension modules for custom types. To offer a HOCON like behavior in Tamaya. 
Something I'm afraid here can only be possible, if @gunnarmorling's (and my) question or concern from the last hangout can be answered or resolved by proving at least JSON or YAML files work and can be properly used on top of this approach. Until then, if you had hundreds of people all claiming "I wrote more lines than you" and this framework can only handle "good old Properties files" while all the other cases like Tamaya work with YAML, JSON, HOCON or even Windows INI files, then this would not be more than an academic thesis nobody can use.

**Comment by keilw** [comment]
So could you rather proof JSON or YAML works instead of wasting time that Eclipse IP team has to spend anyway and gets paid for?

**Comment by struberg** [comment]
How do you come to the conclusio that Romain didn't contribute anything?
He wrote the whole ConfigBuilder and the programmatic API in June 2016
https://github.com/struberg/javaConfig/pull/2/commits

Yes, this sadly didn't get pulled over in a clean way but instead was just copied and thus important IP provenance was destroyed. But that doesn't undo his great contributions.

**Comment by keilw** [comment]
There were other contributions that did not show because e.g. a PR was created by the same person who then merged it;-) The Eclipse organization now counts all contributions either by push or those who requested a PR. Either the Eclipse way in each file or maybe along Gunnar's suggestions (and how it is practiced in projects like Hibernate) a contribution list would be good. It is too tedious to mention every single person or company one by one, that's why other lists exist. If he was the initial creator of a particular class then maybe that could say that like the TCK says already (or e.g. the samples project started by Antonio) but e.g. the Config interface makes a clear impression like Emily started it from scratch (with inspiration or help by others along the road)

**Comment by OndrejM** [comment]
> @keilw Please show us the Red Hat project you or others forced the maintainer to change this into ways you suggested or e.g. Spring may do?

The situation with Weld/CDI is not the same as with Eclipse MicroProfile. CDI spec and Weld project are both **owned** by Red Hat (they hold the IP and copyright). By contributing, you implicitly agree to grant the copyright to them. It is similar in Payara project, but to contribute to Payara, you have to sign a [contributor license agreement ](https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md). The copyright is then attributed to Oracle (the original author) and the Payara foundation (only updated and new files).

If I take Payara and the Payara foundation, which owns the projects resources, as an example, then we would attribute copyright to Eclipse foundation. However, the Eclipse LA states: "You still own Your Contributions, and except for the licenses provided for in this ECA, You reserve all right, title and interest in Your Contributions". Therefore it is OK to attribute the copyright to the original author of a file (an individual or a company or both) and attribute to the parties mentioned as authors later (via the @author tag).

Therefore I suggest the following header as an example:

```
Copyright (c) 2016-2017 {creator's name/s}, {optionally authors employers}. and other authors mentioned by the @author tag below.

@author {editor's name}
@auhor {another editor's name}
```

As an example, if I was the original author, and Emily and Mark contributed (significantly) later, then it would read:

``` 
Copyright (c) 2016-2017 Ondrej Mihályi, Payara Services Ltd.. and other authors mentioned by the @author tag below.

@author Emily Yiang
@author Mark Struberg
```

**Comment by keilw** [comment]
That is pretty much like all Red Hat projects.
And while Red Hat may be the Spec Lead (that is another reason why you see it in the lead of e.g. Weld) it is far from being the only contributor. 

What you suggested seems OK. If e.g. you are an individual contributor but working for Payara and it insists being mentioned, then it sounds fine to list both. There are several "IBM and Red Hat" ones in e.g. the conference example. And there RAT is applied to check for the license "signature" of Apache in every file, but the detailed structure or headers and contribution history can be different, theoretically in every file.

**Comment by OndrejM** [comment]
Thanks, @keilw. I take it as a +1.
Would others mark my suggestion above with +1 or -1 emoticon? If we have an agreement, we can close all the related issues and bring it to a higher level out of config spec. 
@struberg @Emily-Jiang @rmannibucau @kwsutter @jclingan @johnament

**Comment by keilw** [comment]
Yes, I placed a Thumbs up above, but to be precise also +1 here.
It seems to match most existing sources here already (minor variation like "by the author tag..." can certainly be added where necessary) and unless the umbrella hangouts and live calls with overall project leads don't decide that a different header (e.g. the "Spring style" e.g. vert.x inherited from its original authors at Pivotal) shall apply to all of MP, let's stick to it here and close all the tickets.

**Comment by struberg** [comment]
@OndrejM What is the difference to just have "Copyright original Authors or their Companies as indicated by the @authors tag" ?

I really don't like this 'initial author + others' style. It is not very community friendly.

**Comment by keilw** [comment]
Yet practiced for nearly 20 years by 300+ Eclipse projects. Somehow that community managed to survive all these years...?;) 
Ask @waynebeaton but he said before there must be a legal entity or a list of legal entities in the header.
Vert.x was started at Pivotal and it had quite a history before being contributed to Eclipse. Even with inspirations from a few other projects this API only started to exist after the Eclipse move had already been decided. Another ancient now Eclipse project Jetty says
`Copyright (c) 1995-2017 Mort Bay Consulting Pty. Ltd.`
Started in 1995, practically when Java did. Neither Apache nor Eclipse Foundation even existed then ;-)
Jetty also has a massive https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/NOTICE.txt with some references dating back to 1996. There are close to 70 contributors, and they work for Teradata and other companies, the main contributor @gregw (also seems a Tomcat committer or at least forked it)  works at a company called WebTide. yet I could not see a "Copyright Webtide, LLC." header or even his name in most of the files. Some people just seem to contribute and care less about the number of "medals on their chest" or in repositories ;-)

**Comment by rmannibucau** [comment]
it is not about medals but about being legal. BTW @keilw all examples you gave are irrelevant for the reasons we mentionned multiple times before. Please don't make us loose our time sharing all the link google can give you and just try to fix the issue.

**Comment by keilw** [comment]
@OndrejM and I made constructive recommendations instead of trying sound like "Build the Wall" over in the US by some folks. Jetty actually goes as far as to use the same Maven Header Plugin I applied to microprofile-samples. as you see in https://github.com/eclipse/jetty.project/blob/6102861755407813dc446f24638a4ad3a434976b/pom.xml
So every header is exactly the same and a variation (if they include header checks) will break the build. 

I understand that some modules may have different legal entities in their headers, so e.g. microprofile-conference (which a different company or person being the main authors of these modules) was treated differently and so should this, but if @rmannibucau was e.g. considered the initial author of ConfigBuilder then put his name (or Tomitribe, or both as @OndrejM suggested in his case) in the header, but not into all the others.

**Comment by struberg** [comment]
Don't give up @rmannibucau, Werner is just throwing random links at all of us.
"If You Can’t Convince Them, Confuse Them" or so

**Comment by keilw** [comment]
Beside @OndrejM or @Emily-Jiang  I am the only one trying to be constructive and not confuse people or slow things down. 300-400 projects live with that so why can't you @rmannibucau, @struberg if Eclipse EMO @waynebeaton keeps telling all of us, how those headers have to be?

**Comment by struberg** [comment]
Again Werner: you don't get the point it seems. 

What if we change the copyright to "Copyright Walt Disney, Sony Pictures and others" ?
According to your guidelines that would be perfectly fine, right?

**Comment by Emily-Jiang** [comment]
What is the conclusion here? In my original version of Config, I have listed many methods but then some methods were removed based on the PR comments and only the small ones left. To be honest, the config concept is very easy to grasp and Archaius, Tamaya, DeltaSpike all have the concept of config source etc. At the moment, it is closer to DeltaSpike as someone said, partially because Mark and Romain commented a lot on the code and I listened. If you guys jump out to say it is from DeltaSpike, I am not going to waste my time to explain again. I don't care my name being listed there. All I would like to see is that the APIs/SPIs are good for developers. Here is the question? "If Alice caved a big round wheel, Bob suggested her to carve a small round one. After Alice have carved a small round one, she was told it was copied from Bob and should hand over to Bob. Should Alice to listen to Bob again? How can Alice and Bob work together in the future?".

**Comment by keilw** [comment]
@struberg Don't be silly, and please keep the scary goodnight stories for your kids. If you wrote "Copyright Walt Disney" at the very least the IP review by Eclipse EMO would question that and force you to fix it to a proper legal entity like your own name, IBM or another that is really involved. 
I contributed to dozens of those CQs now (in IPZilla) and for various reasons, e.g. not accepting a license like GPL some CQs had to be withdrawn or were denied. While all others succeeded, but it can take up to a year or more, e.g. https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9154 (filed in Jan 2015, rejected in December 2015) If you make the life of Sharon and others harder then the review will take longer and so will acceptance of a module in question.

**Comment by struberg** [comment]
Hi Emily!

This discussion is just about moving the "Copyright" header to something more community friendly. It's not about authorship. Rest ensured that your name will remain listed as you contributed a whole lot! Lots of code, JavaDocs, cleaned up and contributed many hours of work and especially an open mind and lots of energy to push this forward. 
You mentioned Archaius, Tamaya and DeltaSpike. Archaius1 didn't have the ConfigSource concept and Archaius2 only adopted it in mid 2015, 4 years after DeltaSpike. I also committed ConfigSource.java etc to Tamaya, so this part is very clear. 

> All I would like to see is that the APIs/SPIs are good for developers.

Yes, that's the spririt I love to see!

Let's remember where we came from: "Copyright Microprofile.io". Of course it was legally wrong as 'Microprofile.io' is not a legal entity. But the focus of this wording was much more on the community, don't you agree? Wayne was about to clarify whether "Copyright original Authors or their Employers" would be legally OK for Eclipse. Let's wait what he brings up.

At all the ASF projects we have no copyright header at all and barely use @author tags - and still all is legally perfectly fine. Because it's licensed under ALv2 anyway, and the code provenance is only needed if someone tries to sue one. And the strict commit rules over at Apache guarantee a good code provenance to cover this case.

**Comment by keilw** [comment]
Both in the JDK at least new elements and all the Java EE JSRs led by Oracle, there is of course the obvious header ("Oracle and or its affiliates") but the @author tags are purged from all of these, too.

The only project under the Eclipse organization (we also had the discussion about it over package and artifact naming) where historically the SpringSource/Pivotal header "Copright by the authors" exists is vert.x, but it was transferred to Eclipse when its author left Pivotal (or its prior names) and I believe joined Red Hat. There was also a lot of politics involved, so he and the vert.x project probably did not want to upset Spring by putting "Copyright Red Hat and others" there. This literally seems the only Eclipse project where no source file refers to one or more legal entities. For reasons Eclipse demands and Wayne or others explained multiple times.

**Comment by keilw** [comment]
As I joined the Eclipse Science WG and subscribed to its mailing list a long time ago, I came across multiple projects that are collaborative efforts by companies and inviduduals from all around the world.
https://github.com/eclipse/january is a good example. It refers to http://www.numpy.org/ as at least as inspirational as DeltaSpike, Tamaya, Typesafe Config or Archaius may be to several elements in this library.  I'm sure some of it was at least "borrowed" from NumPy though you cannot directly copy Python to Java code in this case.
The headers are highly diverse with `Copyright (c) 2015 UT-Battelle, LLC.`  or `Copyright (c) 2012, 2016 Diamond Light Source Ltd.` just being two examples. Those projects are inspired by an academic background I'd imagine at least @struberg should be familiar with (working a lot at universities) and they also use headers, maybe a different one per file, so why shouldn't that work here?

**Comment by os890** [comment]
imo it's pretty clear how to do it. see e.g.: http://svn.apache.org/repos/asf/myfaces/trinidad/trunk/NOTICE

**Comment by keilw** [comment]
@os890 You seem to be commenting on https://github.com/eclipse/microprofile-config/issues/95 here, but it looks fine for what John asked there.

**Comment by gregw** [comment]
On 15 March 2017 at 04:53, Werner Keil <notifications@github.com> wrote:

> Copyright (c) 1995-2017 <1995%202017> Mort Bay Consulting Pty. Ltd.
> Started in 1995, practically when Java did. Neither Apache nor Eclipse
> Foundation even existed then ;-)
>

I wrote the first version on Java 0.9 Beta!    But Mort Bay did exist at
that time!

The way I explain copyright for the jetty project is as follows.   The
CLA's and open source licences we use do not assign copyright, they simply
grant a licence to use a copy right work and warrant that the contributor
has the authority to do so.

We make or require no formal effort to assign copyright to Mort Bay, but
operate under the mode that almost all contributions are under a banner
that do assign copyright to Mort Bay.    However, there is no prohibition
on other copyrights and indeed our NOTICE.txt files says:

The Jetty Web Container is Copyright Mort Bay Consulting Pty Ltd
unless otherwise noted.


It is just that we ask the contributors we employ to direct copy right to
Mort Bay (which is a part owner of Webtide, who employs most contributors
that do not work for Mort Bay directly).    But this is not a hard
requirement. We do have some files that do 'note otherwise', for example
the UnixCrypt.java file has "Copyright (c) 1996 Aki Yoshida. All rights
reserved."  in the header together with an explicit grant of licence.

We have on occasions had contributions that have had other copyrights in
the header.   Our response has been to accept them if they are significant,
but then eventually replace them with our own implementation over time....
or to not accept them if they are trivial as we are dubious that the
correction of a simple bug would extend any copyright over any part of the
code.

My understanding is that without an explicit formal copyright assignment,
that there are probably parts of the code that could be argued are not
copyright Mort Bay.  However there only way such an assertion could be
tested would be through an expensive court case, where the claim would
suffer somewhat by the lack of any prior effort to enforce copyright and
the huge body of copyright Mort Bay work that is likely derived from.  Even
if such a claim was successful, then it would not be of any real
significance because all contributions are under CLA and licences that
grants a perpetual right to use.... unless the contribution was incorrectly
made.

The only time we believe that copyright does come into play is when
licences are to be changed.  For example, when we added to the EPL to the
jetty project we made and effort to contact all listed and probably
copyright holders to give them an opportunity to assert copyright and
dispute the additional licence grant.

So if you do have files in your project that have copyright headers that
you don't want to be there, or that are just different, then my advice
would not be to unilaterally remove them.   If you are satisfied that they
have been contributed correctly, then regardless of the copyright they are
covered by your open source licence and all is good.  If they have not been
contributed correctly, then it is probably more than just the copyright
header that would be in doubt, so just removing the header would be rather
dubious.  If you can't get the contributor to clarify the contribution,
then re implementation is the best way to get a clean copy with copyright
assigned as you like.

cheers

-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by struberg** [comment]
Hi Greg! 
I had a similar discussion with @waynebeaton already. The "Copyright $BigCorp" _could_ be interpreted as CLA like situation. The "and others" as unspecified (!) shared copyright pool like. But this is clearly not intended in our case. 
In our case it's more like "Copyright whoever wrote parts of that stuff". Of course everybody grants rights "Under the License" (ALv2 here). But still only the original authors own the originary Copyright on exactly those parts they wrote.
This especially the case for all parts which got copied over from ASF projects, which require attribution.

That's a subtle difference, but an important one from a legal pov. And we should not take this lightly. It's easy to fix though...

LieGrue,
strub

**Comment by keilw** [comment]
>  For example, when we added to the EPL to the Jetty project
So it was also ALv2 first.

@gregw Thanks for the detailed input from a project that existed for quite some time both outside and inside Eclipse.

**Comment by Emily-Jiang** [comment]
If this is Config JSR, what copyright will Oracle use then?

**Comment by gregw** [comment]
On 15 March 2017 at 09:27, Werner Keil <notifications@github.com> wrote:

> So it was also ALv2 first.
>
> Since you asked:  Jetty has been under many licences over the years.  I
don't think version 1.x even had a licence; 2.x is under our own licence;
5.x is ALv2; 7.x onwards is dual APv2 EPL.

cheers

-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by keilw** [comment]
@Emily-Jiang I can't say because there is none and nobody at Oracle is currently willing to confirm what may or may not go into Java EE 9, but JSON-B has its RI under Eclipse, so you can see the license headers of files like https://github.com/eclipse/eclipselink.runtime/blob/master/moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/AttributeNode.java

**Comment by OndrejM** [comment]
I converted license headers for all files that attributed copyright to Eclipse members or Payara via[ this commit](https://github.com/eclipse/microprofile-config/commit/a2571425cc6a2e293b7f209ada32932737fd5b78). 

I didn't touch the following files, which attribute copyright to other parties or have no copyright header:

Attributed to IBM ( @Emily-Jiang, please fix those, probably mentioning IBM in the NOTICE file)
- AutoDiscoveredConfigSourceTest
- most files in the spi package, like ConfigProviderResolver, including package-info.java
- all files in the root api package, like Config, including package-info.java
- main README.adoc file

Attributed to @struberg:
- api/src/main/java/org/eclipse/microprofile/config/inject/package-info.java

No copyright:
 - bnd.bnd in api (authors @Emily-Jiang  and @struberg )

**Comment by Emily-Jiang** [comment]
@struberg @OndrejM Did you address all copyright issues? Should we close this issue?

**Comment by Emily-Jiang** [comment]
This is fixed.
