### ISSUE TITLE
@ConfigProperties Javadoc clarification

### ISSUE THREAD

**Issue by Joseph-Cass** [eclipse/microprofile-config#681]
The spec includes a Bean Defining Annotation (`@Dependent`) for the @ConfigProperties example:
https://github.com/eclipse/microprofile-config/blame/master/spec/src/main/asciidoc/configexamples.asciidoc#L420-L431

But the Javadoc for the class doesn't:
https://github.com/eclipse/microprofile-config/blob/4bda7c776e00a3baf41af728215900e02485de2c/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperties.java#L42-L52

Should the Javadoc include a Bean Defining Annotation too?

**Comment by radcortez** [comment]
We can probably remove it from the spec. It is not required.

**Comment by Emily-Jiang** [comment]
No, we should not remove it from spec and it is required. The bean defining annotation should be there to indicate this only works with CDI beans. In MP Config, this annotation only works with a CDI bean as it is a qualifier. 

Since `@Dependent` will be automatically the default if no other bean defining annotation is present. It is a given if there is a beans.xml for instance. I think it works better if we add that to javadoc to make it clearer.
