### ISSUE TITLE
Remove OSGi annotations from the API

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile-config#716]
The OSGi annotations added in https://github.com/eclipse/microprofile-config/pull/381/, cause annoying compiler warnings. 

The issue is that we mark the OSGi dependencies as provided and a reference to `org.osgi.annotation.bundle.Requirement.Resolution#OPTIONAL` is missing from the dependencies when compiling a project that uses `@ConfigProperty`.

Adding the OSGi dependency as compile does fix the issue, but I believe an MP API should not transitively push this kind of dependency to their consumers (especially if they are not using OSGi).

This can be reproduced just by using the MP Config API JAR, use the `@ConfigProperty` annotation and compile code with warnings on: `-Dmaven.compiler.showWarnings=true`. It generates the following warning:

```
[WARNING] unknown enum constant org.osgi.annotation.bundle.Requirement.Resolution.OPTIONAL
  reason: class file for org.osgi.annotation.bundle.Requirement$Resolution not found
```

This causes confusion to users, and we should remove this warning.

**Comment by Emily-Jiang** [comment]
@rotty3000 this is the annotation you added for OSGi CDI. If I remembered correctly, this annotation should not cause any issues for non-OSGi environament. Apparently it caused problems for Quarkus. We might have to remove these annotations if this can't be resolved.

**Comment by radcortez** [comment]
Just a clarification, this has nothing to do with Quarkus. You can reproduce the warning just with the MP Config API jar and with compiler warnings turned on.

**Comment by rotty3000** [comment]
Though this is _not a runtime limitation in any way_, I don't think I know a way to prevent the compiler warning based on how the annotation is designed (to use a enum as property value).

I would ask @bjhargrave for advice on this.

**Comment by bjhargrave** [comment]
This is because the the osgi annotations jar is not a compile scope dependency of the eclipse microprofile config jar. Generally tools need to see annotation definitions to see if they may be meta-annotated with annotations the tool needs to process. Javadoc wants to look for Documented meta-annotations, Bnd wants to look for meta-annotations it must process. Javac is likely also wanting to do the same. Thus the warning to indicate there is an annotation whose definition cannot be examined.

The solution is for the eclipse microprofile config jar to have a compile scope dependency on the osgi.annotation jar which would provide javac, javadoc, etc. which visibility to the annotation definitions.

Based upon this feedback, we are making updates to the OSGi api jars about to be published for the Compendium Release 8 to make sure the maven pom metadata properly indicates the compile scope dependency on osgi.annotation.

@Emily-Jiang I can prepare a PR for eclipse microprofile config for this change (compile scope dependency on osgi.annotation) if you want.

**Comment by radcortez** [comment]
Yes, I know that adding the OSGi dependency would fix the issue.

On the other hand, I think that we need to be very careful about this decision. Yes, I know it should be harmless, but by principle, I believe that the MP APIs shouldn't push any additional dependencies. This creates a blurred boundary on what it is acceptable to add as metadata from external APIs and what is not.

If other APIs would like to add their own metadata, should we add it as well and include their dependencies?

**Comment by bjhargrave** [comment]
This is not pushing any runtime dependencies. This is about preventing compiler warnings (which are harmless but we should support clean builds) via compile time dependencies.

The OSGi annotations allow the artifacts to be OSGi-ready. A number of Microprofile stakeholders and users use OSGi as a module system and need the artifacts to be OSGi-ready. Without the OSGi annotations in the source code, the OSGi metadata would need to be manually maintained in the pom file (or external bnd file) and this would become out of date as developers forget or don't know to update the information. This is the value of annotations: the information is in the source code where the developers are working.

> If other APIs would like to add their own metadata, should we add it as well and include their dependencies?

This is a slippery-slope argument and not very compelling. We have an actual need _now_ for OSGi metadata in the artifacts. If other module systems (e.g. JPMS) need source code (e.g. module-info.java), I am sure Microprofile will do what is needed for the stakeholders and users of Microprofile. This sort of decision is best made when there are actual expressed needs rather than attempting to wave them away up front.

**Comment by famod** [comment]
I'm not at all familiar with the internals of MP Config, but have you ever considered shipping two flavours? One with and one without OSGi?

**Comment by jorsol** [comment]
Yes, please remove the OSGi annotations, any annotation that makes use of an `enum` creates an unnecessary dependency.

While using annotations improves the maintenance of OSGi metadata, there is an issue when those annotations use enums, I honestly think that until those annotations remove the enum coupling, the OSGi metadata should be maintained in the pom file or externally.

**Comment by Emily-Jiang** [comment]
@rotty3000 please see the above comments.

**Comment by renegrob** [comment]
I added the following snipped to my code to get rid of this annoying warning:
```java
package org.osgi.annotation.bundle;

/**
 * Workaround for "warning: unknown enum constant Resolution.OPTIONAL" during compilation. This class is not used at runtime.
 * See also https://github.com/eclipse/microprofile-config/issues/716
 */
@SuppressWarnings("unused")
public class Requirement {
    public enum Resolution {
        OPTIONAL
    }
}
```
While this works it is an ugly hack. My question is, if this dependency is not required then why is it referenced. Somewhere seems to be a false dependency scope or a class in the wrong dependency.  Or the package that depends on `org.osgi.annotation.bundle` should be moved to a separate artifact that then depends on it. Having warnings in the build that you just need to ignore and can't even switch off easily is just super annoying.

**Comment by jorsol** [comment]
The problem is those optional (or compile-only) annotations should NEVER use enums, so until the OSGi annotations are fixed and remove the enum dependency this will be a problem.

Enums make the code more type-safe, but if the annotations are intended to be used optionally or just at compile-time (for generation of metadata or source code), then using enums is definitely a bad practice.

**Comment by Emily-Jiang** [comment]
@jorsol the dependency should be marked `compiled` instead of `provided`. Can make that change to get rid of the warning.

**Comment by jorsol** [comment]
The problem is that the dependency should **not** be of scope `compiled`, it's an optional dependency, the dependency should not end up in the final artifacts just by transitivity... yes, that will get rid of the warning, but the proper fix should be that the annotations get rid of the enums, in other words, the fix should be done in the annotations of the OSGi project.

I can just add the dependency (or if it's declared as `compile` this is pulled transitively):
```xml
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.annotation.bundle</artifactId>
      <version>1.1.1</version>
    </dependency>
```
The result will be that a dependency ends up in the final application directory for no good reason. This is especially true for an annotation that the main purpose is to generate a bundle's manifest, the is no use of the dependency beyond that.

**Comment by famod** [comment]
FTR, I'm using following workaround in my Quarkus project (in root parent pom.xml):
```xml
        <!-- workaround for https://github.com/quarkusio/quarkus/issues/19970 -->
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.annotation</artifactId>
            <version>7.0.0</version>
            <scope>provided</scope>
        </dependency>
```
This way it at least doesn't end up in the production jar.

**Comment by bjhargrave** [comment]
FYI, I am working a fix to the OSGi annotations to replace use of enum types with String along with a corresponding fix to Bnd to support this change.
