### ISSUE TITLE
How to distinguish between metrics/health endpoints from different apps running on same server

### ISSUE THREAD

**Issue by dbnex14** [eclipse/microprofile-config#724]
It is a basic question but I am unable to find information or resolve the issue I am having with Microprofile.  I have spent hours goiing through various articles, StackOverflow etc, none of which touches on this subject which was a big surprise for me.

Here is the issue I am having.  I annotated my method using Microprofile annotations like so:

	@Counted(name="retrievexxx-count", displayName="Number of xxx calls", description="Total number of xxx calls serviced")
	@Metered(name="retrievexxx-meter", displayName="xxx average throughput", description="Average throughput of xxx calls being serviced")
	public MyObject retrieveXXX() throws APIException { ... }

In case of  Spring Actuator, it will `/actuator/appName` context path to the URL automatically, So I will end up with clear distinction btw metrics by app like:

```
https://myserver/actuator/app1/metrics
https://myserver/actuator/app1/health

https://myserver/actuator/app2/metrics
https://myserver/actuator/app2/health
```

... etc.  If I had 10 applications on this server all using actuator, I clearly can see which `/metrics` come from which app.  Same for `/health` endpoint.

I dont see this happening with Microprofile. So, I end up with say /metrics url like

```
https://myserver/metrics
https://myserver/health
```
, and all 10 apps are crammed under the single endpoint.

Is there a way in Microprofile to have `/health` and `/metrics` endpoints exposed like:

```
https://myserver/myApi/metrics
https://myserver/myApi/health
```

so that I know clearly that these are comming from `myApi` app?

**Comment by Emily-Jiang** [comment]
The best practice for doing microservices is one app per pot. Especially for Health, k8s will treat pod as a smallest unit. Because of this, it does not give you much value if you separately monitor each app's health status. In the scenario of one app being live, if another one in the same pot not alive, k8s will recycle the pot regardless. 

Anyway, you can take this conversation to the corresponding repos MicroProfile [Metrics](https://github.com/eclipse/microprofile-metrics) and [Health](https://github.com/eclipse/microprofile-health) accordingly. This was discussed a few times in the past. 

Since this is not about this spec, I will close this issue from here.
