### ISSUE TITLE
Open Liberty 21.0.0.12-beta: MicroProfile Config 3.0 Compatible Certification Request

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#725]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 21.0.0.12-beta](https://github.com/OpenLiberty/open-liberty/releases/tag/gm-21.0.0.12-beta)
- [x] Specification Name, Version and download URL:<br/>
   [MicroProfile Config 3.0](https://search.maven.org/search?q=g:org.eclipse.microprofile.config%20AND%20a:microprofile-config-api%20AND%20v:3.0)
- [x] Public URL of TCK Results Summary:<br/>
  [MicroProfile Config 3.0 TCK result](https://openliberty.io/certifications/microprofile/5.0/config/3.0/21.0.0.12-beta-TCKResults.html)
- [x] Java runtime used to run the implementation:<br/>
  Java 8 and Java 11
- [x] Any Additional Specification Certification Requirements:<br/>
  n/a
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  [Here](https://openliberty.io/certifications/microprofile/5.0/config/3.0/21.0.0.12-beta-TCKResults.html)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
For the TCK Results, shouldn't we be specifying the final version of the Config 3.0 specification (not RC5)?  Or, maybe this is in the process of being updated since the ballot is under way?

Also, did you want to be specific on the Java runtime project/product that was used?  That is, OpenJDK with Hotspot, or whatever was used.  We do that with the CCRs for Jakarta. I wasn't sure what was required for MicroProfile CCRs.

**Comment by radcortez** [comment]
> For the TCK Results, shouldn't we be specifying the final version of the Config 3.0 specification (not RC5)? Or, maybe this is in the process of being updated since the ballot is under way?
> 

Correct. Because the final version is not released yet, there is not public repository to get it from, so the only way to do the CCR is with the RC. Once a final is out a new CCR may be submitted for the final version.

> Also, did you want to be specific on the Java runtime project/product that was used? That is, OpenJDK with Hotspot, or whatever was used. We do that with the CCRs for Jakarta. I wasn't sure what was required for MicroProfile CCRs.

I believe we only require to state the Java runtime version.

**Comment by Emily-Jiang** [comment]
I also added a similar comment [here](https://github.com/eclipse/microprofile-metrics/issues/651#issuecomment-964635946) yesterday.

**Comment by kwsutter** [comment]
> > For the TCK Results, shouldn't we be specifying the final version of the Config 3.0 specification (not RC5)? Or, maybe this is in the process of being updated since the ballot is under way?
> 
> Correct. Because the final version is not released yet, there is not public repository to get it from, so the only way to do the CCR is with the RC. Once a final is out a new CCR may be submitted for the final version.
> 

Yes, I understand.  Since we're housing the Specs in Maven (vs the website like we do with Jakarta EE), this referencing of the final spec is a bit more complicated.  As I replied to @Emily-Jiang in the other issue, maybe you should just use both references -- the RC version and the expected final version url.  And, after the spec goes final, then this CCR could be updated to remove the RC reference.  There should be no requirement to submit another CCR.  

> > Also, did you want to be specific on the Java runtime project/product that was used? That is, OpenJDK with Hotspot, or whatever was used. We do that with the CCRs for Jakarta. I wasn't sure what was required for MicroProfile CCRs.
> 
> I believe we only require to state the Java runtime version.

I understand it may not be a requirement, but it might be helpful down the road to know explicitly which Java runtime was used for the CCR.  As we all know, there are getting to be many, many different Java runtime deliverables available for use.  It might be good to know which one was used for the CCR.

**Comment by Emily-Jiang** [comment]
I have put the final spec url on the CCR as suggested by @kwsutter. Close this one. In the future CCRs, we will try to add os details to give more info.
