### ISSUE TITLE
TCK does not work with CDI 4.0

### ISSUE THREAD

**Issue by tnagao7** [eclipse/microprofile-config#737]
**Describe the bug**

When run on a CDI 4.0 runtime, MicroProfile Config 3.0.1 TCK fails with an "unsatisfied dependencies" error.

The cause of failure is a [change](https://github.com/eclipse-ee4j/cdi/issues/500) in the semantics of an empty `beans.xml`:

* In CDI 3.0 (Jakarta EE 9), an empty `beans.xml` implies `bean-discovery-mode="all"`
* In CDI 4.0 (Jakarta EE 10), an empty `beans.xml` implies `bean-discovery-mode="annotated"`

Deployments of failing tests have an empty `beans.xml`:

https://github.com/eclipse/microprofile-config/blob/3.0.1/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java#L101

```java
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
```

A TCK improvement for allowing the combination of Config 3.0 and CDI 4.0 (Jakarta EE 10) would be helpful.  Although Config 3.0 is aligned with CDI 3.0 (Jakarta EE 9) for javax/jakarta namespace transition, this does not necessarily mean that Config 3.0 is only available on a CDI 3.0 runtime.  Since CDI 3.0 (Jakarta EE 9) is just a tooling release, there is a broader demand for the combination with CDI 4.0 (Jakarta EE 10).

**Comment by manovotn** [comment]
This is superseeded by https://github.com/eclipse/microprofile-config/issues/742 and will be fixed by https://github.com/eclipse/microprofile-config/pull/743 (@tnagao7 do let me know if that's not the case!)
I only noticed this issue after doing my own investigation and creating an issue and a PR,
Therefore, I think we can close this issue.
